# BASIC PYTHON

In [112]:
import platform
import numpy as np
import pandas as pd
print(platform.python_version()) #check the version

3.6.4


In [3]:
print("Hello World!")

Hello World!


In [4]:
#using print
print(2+5) #tanpa print cuma yg terakhir yang ditampilkan
print(3-4)

7
-1


### VARIABLE

In [16]:
x = 10
y = 3
print(x)
print(y)
print(x+y)

10
3
13


Arithmatic :
** => pangkat
// => pembagi
% => modulo

In [11]:
print(-x)
print("pangkat",x**y) 
print("pembagi atau floor ",x//y)
print("modulo",x%y)

print(10-5*3) #aritmatik biasa
print((10-5)*3) #yg dikurung yang duluan dihitung

-10
pangkat 1000
pembagi atau floor  3
modulo 1
-5
15


### BOOLEAN
(bool)

In [13]:
#BOOLEAN 1
print(True)
print(type(True)) #melihat type data True dan False
print(type(False))
print(type("True")) #tipe data string kalau mengunakan ""

True
<class 'bool'>
<class 'bool'>
<class 'str'>


In [25]:
#BOOLEAN 2
print(x==y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)


False
True
True
False
True
False


In [26]:
#BOOLEAN 3
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t != f)

<class 'bool'>
False
True
False
True


### LIST

In [28]:
Fam = [2,3,4,5,6,7] #menyimpan banyak data ke dalam variabel = list
print(Fam)
type(Fam) #output tipe data list

[2, 3, 4, 5, 6, 7]


list

In [77]:
Data = [["Bob", 160],["Charlie",150],["Brian",140.5]]
#tipe data
#tipe list pertama
#tipe bob
type(Data) #variable data
type(Data[0]) #index pertama di list Data
type(Data[0][0]) #index pertama di list Data[0]

str

In [41]:
print(Data[0][1] + Data[1][1]) #menambahkan data dalam list pada list

310


In [48]:
nums = list(range(7)) #range is built-in function
print(nums)
print(nums[2:4])
print(nums[2:]) #dari index 2 sampai selesai
print(nums[:4]) #dari  index 0 s.d index 3
print(nums[:]) #pilih semua element
print(nums[:-1])
nums[2:4] = [8,9] #mengganti index[2] dan index[3] menjadi 8 dan 9
print(nums)

[0, 1, 2, 3, 4, 5, 6]
[2, 3]
[2, 3, 4, 5, 6]
[0, 1, 2, 3]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5]
[0, 1, 8, 9, 4, 5, 6]


In [60]:
#Option 1
print("Bob's Height :",Data[0][1]) #akan ditampilkan apa adanya, ditampilkan nilai dr data[0][1]
print("Brian's Height :",Data[2][1])

#Option 2
print("Bob's Height : {}".format(Data[0][1]))#ditampilkan apa adanya
print("Bob's Height :{:0.2f} ".format(Data[0][1])) #ditampilkan sesuai format {:0.2f} => float 2 angka dibelakang koma
print("Bob's Height :{:0.2f} dan Brian's Height : {:0.3f}".format(Data[0][1], Data[2][1])) #lebih dari satu data yang di insert
print("{:s}'s Height :{:0.2f} dan {:s}'s Height : {:0.3f}".format(Data[0][0], Data[0][1],Data[2][0],Data[2][1])) 

print("Bob's Height :%0.2f dan Brian's Height : %0.3f" %(Data[0][1], Data[2][1]))

Bob's Height : 160
Brian's Height : 140.5
Bob's Height : 160
Bob's Height :160.00 
Bob's Height :160.00 dan Brian's Height : 140.500
Bob's Height :160.00 dan Brian's Height : 140.500
Bob's Height :160.00 dan Brian's Height : 140.500


In [79]:
##APPEND DATA TO LIST##
#Data.append(["Sarah",170])
#Data.append(["Anna",190])
#Data
#print(Data.pop()) #Data.pop() keluarkan data paling akhir ditambahkan
#print(Data.pop(0)) #pop index 0
Data

[['Bob', 160],
 ['Charlie', 150],
 ['Brian', 140.5],
 ['Sarah', 170],
 ['Anna', 190]]

In [81]:
a =[1,2,3,4]
a.insert(1,9) #memasukkan data 9 ke index[1]
a

[1, 9, 2, 3, 4]

## FUNCTION

-Built in function :max(),min(),len()
help(max)

In [230]:
def label_height(height):
    if height > 150:
        label = 'tinggi'
    elif height <= 150 & height >=145: #bisa and dan '&'
        label = 'kurang tinggi'
    else:
        label = 'lain-lain'
    return label #return variabel yg ada di dalam fungsi,bukan nama fungsi
label_height(146) #pemanggilan fungsi
label_height(Data[0][1])


'tinggi'

In [100]:
print(list(map(label_height, Fam))) #memasukkan lebih dari satu data
#list digunakan untuk meconvert map menjadi list
Fam

['lain-lain', 'lain-lain', 'lain-lain', 'lain-lain', 'lain-lain', 'lain-lain']


[2, 3, 4, 5, 6, 7]

In [232]:
name_list = [row [0] for row in Data]
height_list = [row[1] for row in Data]
print(name_list)
print(height_list)
#b = list(map(label_height,height_list))

['Bob', 'Charlie', 'Brian', 'Sarah', 'Anna']
[160, 150, 140.5, 170, 190]


TypeError: unsupported operand type(s) for &: 'int' and 'float'

In [105]:
print(list(map(lambda x : x+100, height_list))) #lambda dummy function

[260, 250, 240.5, 270, 290]


## LOOPING

In [107]:
num = [0,1,2,3,4]
squares = [x**2 for x in num] #without dummy function
squares

[0, 1, 4, 9, 16]

In [108]:
print(list(map(lambda x : x**2, num)))

[0, 1, 4, 9, 16]


## METHOD
misal punya data string. ada fungsi2 tidak bisa diimplementasikan ke string. Maka digunakan method. 
capitalized(),upper(), lower(),strip()

In [119]:
n = "Hello world"
print(n.upper())
n = "Hello world"
print(n.strip())


HELLO WORLD
Hello world


In [118]:
#Convert list to numpy array
height_array = np.array(height_list)
print(height_array)
print(height_array + 100)

[160.  150.  140.5 170.  190. ]
[260.  250.  240.5 270.  290. ]


In [130]:
x = np.array([[1,2,3],[4,5,6]])
type(x)
print(x.dtype)
print(x.shape)

int32
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
print(type(x))
print(type(x.tolist()))
print(type(np.array(x)))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [135]:
print(x.flatten())
print(x.transpose())
print(x.reshape([2,3]))
x

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
print(x.sum(axis=0)) #acuan row ditambahin ke bawah(kolom)
print(x.sum(axis=1)) #acuan kolom ditambahin ke samping(row)
print(x.max(axis=1))
print(x.std(axis=1))
print(x.std(axis=0))


[5 7 9]
[ 6 15]
[3 6]
[0.81649658 0.81649658]
[1.5 1.5 1.5]


## DICTIONARIES


In [143]:
europe = {'spain':'madrid','fracnce':'paris','germany':'berlin','norway':'oslos'}
type(europe)

dict

In [156]:
code=['US','AUS','JPN','IN','RUS','MOR','EG']
names=['United States','Australia','Japan','India','Russia','Morocco','Egypt']
dr=[True,False,False,False,True,True,True]
cpc=[809,731,588,18,200,70,45]
dicts = dict(zip(code,names))
my_dict = {'ctrcode':code,'country':names,'drives_right':dr,'cars_per_cap':cpc}
dicts
my_dict

{'cars_per_cap': [809, 731, 588, 18, 200, 70, 45],
 'country': ['United States',
  'Australia',
  'Japan',
  'India',
  'Russia',
  'Morocco',
  'Egypt'],
 'ctrcode': ['US', 'AUS', 'JPN', 'IN', 'RUS', 'MOR', 'EG'],
 'drives_right': [True, False, False, False, True, True, True]}

<class 'pandas.core.frame.DataFrame'>
   cars_per_cap        country ctrcode  drives_right
0           809  United States      US          True
1           731      Australia     AUS         False
2           588          Japan     JPN         False
3            18          India      IN         False
4           200         Russia     RUS          True
5            70        Morocco     MOR          True
6            45          Egypt      EG          True


## PANDAS

In [227]:
cars = pd.DataFrame(my_dict)
print(type(cars))
print(cars)

<class 'pandas.core.frame.DataFrame'>
   cars_per_cap        country ctrcode  drives_right
0           809  United States      US          True
1           731      Australia     AUS         False
2           588          Japan     JPN         False
3            18          India      IN         False
4           200         Russia     RUS          True
5            70        Morocco     MOR          True
6            45          Egypt      EG          True


In [163]:
cars.shape #melihat dimensi

(7, 4)

In [165]:
len(cars) #panjang ke bawah (row)

7

In [171]:
cars.head(3)  #memunculkan data dari atas
cars.tail(3)  #memunculkan data dari yang palinga akhir

cars_per_cap  country ctrcode  drives_right
4           200   Russia     RUS          True
5            70  Morocco     MOR          True
6            45    Egypt      EG          True

In [189]:
print(cars.dtypes)
cars.info() #lebih detail dari dtypes
cars.describe() #summary statistics

cars_per_cap     int64
country         object
ctrcode         object
drives_right      bool
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
cars_per_cap    7 non-null int64
country         7 non-null object
ctrcode         7 non-null object
drives_right    7 non-null bool
dtypes: bool(1), int64(1), object(2)
memory usage: 255.0+ bytes


cars_per_cap
count      7.000000
mean     351.571429
std      345.595552
min       18.000000
25%       57.500000
50%      200.000000
75%      659.500000
max      809.000000

In [192]:
cars_id=cars.set_index("ctrcode")
cars_id

cars_per_cap        country  drives_right
ctrcode                                           
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False
IN                 18          India         False
RUS               200         Russia          True
MOR                70        Morocco          True
EG                 45          Egypt          True

### SLICES AND DICE

In [204]:
print(cars['country']) #jadi series


0    United States
1        Australia
2            Japan
3            India
4           Russia
5          Morocco
6            Egypt
Name: country, dtype: object


In [207]:
print(cars[['country']]) #bentuknya dataframe

<class 'pandas.core.frame.DataFrame'>
         cars_per_cap        country  drives_right
ctrcode                                           
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False


### LOC dan iLOC

In [215]:
print(cars_id.loc['JPN']) #memilih data berdasarkan row tertentu
print(cars_id.iloc[0]) #memilih data berdasarkan index dari row
print(cars_id.loc[['RUS','MOR'],['country']]) #memfilter row yg rusia dan morocco sam kolom country
print(cars_id.iloc[[3,5],[1,2]])

cars_per_cap      588
country         Japan
drives_right    False
Name: JPN, dtype: object
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
         country
ctrcode         
RUS       Russia
MOR      Morocco
         country  drives_right
ctrcode                       
IN         India         False
MOR      Morocco          True


### WHERE CLAUSE

In [224]:
print(cars_id[(cars_id.cars_per_cap > 100) & (cars_id.country == "Australia")])

         cars_per_cap    country  drives_right
ctrcode                                       
AUS               731  Australia         False


In [222]:
print(cars_id[(cars_id.cars_per_cap > 100) | (cars_id.country == "Australia")])

         cars_per_cap        country  drives_right
ctrcode                                           
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False
RUS               200         Russia          True


### SORTING

In [226]:
cars_id.sort_values(by=['cars_per_cap'])
cars_id.sort_values(by=['cars_per_cap'],ascending=False)

cars_per_cap        country  drives_right
ctrcode                                           
US                809  United States          True
AUS               731      Australia         False
JPN               588          Japan         False
RUS               200         Russia          True
MOR                70        Morocco          True
EG                 45          Egypt          True
IN                 18          India         False