In [9]:
import pandas as pd
import statsmodels.formula.api as smf
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import sklearn
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [1]:
df = pd.read_csv("http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv",index_col=0)

NameError: name 'pd' is not defined

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.shape
df.info()

In [ ]:
plt.scatter(x='TV',y='sales',data=df)
plt.scatter(x='radio',y='sales',data=df)
plt.scatter(x='newspaper',y='sales',data=df,color='r')
plt.show()

In [8]:
lm = smf.ols(formula='sales~newspaper', data=df).fit()

NameError: name 'df' is not defined

In [ ]:
lm.params #koefisien intercept dan tv

In [6]:
x_new = pd.DataFrame({'newspaper':[50,70,108.8]})
x_new.head()

newspaper
0       50.0
1       70.0
2      108.8

In [7]:
lm.predict(x_new) #kalau newspaper 50,y brp. memperediksi.

NameError: name 'lm' is not defined

In [4]:
x_n = pd.DataFrame({'newspaper':[df.newspaper.min(),df.newspaper.max()]})
x_n.head()

NameError: name 'df' is not defined

In [5]:
pred = lm.predict(x_n)
pred

NameError: name 'lm' is not defined

In [67]:
lm.rsquared

0.05212044544430516

In [68]:
lm.conf_int()

0          1
Intercept  11.125956  13.576859
newspaper   0.022005   0.087381

In [69]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.052
Model:                            OLS   Adj. R-squared:                  0.047
Method:                 Least Squares   F-statistic:                     10.89
Date:                Mon, 28 May 2018   Prob (F-statistic):            0.00115
Time:                        13:12:44   Log-Likelihood:                -608.34
No. Observations:                 200   AIC:                             1221.
Df Residuals:                     198   BIC:                             1227.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.3514      0.621     19.876      0.000      11.126      13.577
newspaper      0.0547      0.017      3.300      0.001       0.022       0.087
==============================================================================
Omnibus:                        6.231   Durbin-Watson:                   1.983
Prob(Omnibus):                  0.044   Jarque-Bera (JB):                5.483
Skew:                           0.330   Prob(JB):                       0.0645
Kurtosis:                       2.527   Cond. No.                         64.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [80]:
lm1 = smf.ols(formula='sales~TV+newspaper', data=df).fit()

In [81]:
lm1.params

Intercept    5.774948
TV           0.046901
newspaper    0.044219
dtype: float64

In [82]:
lm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.646
Model:                            OLS   Adj. R-squared:                  0.642
Method:                 Least Squares   F-statistic:                     179.6
Date:                Mon, 28 May 2018   Prob (F-statistic):           3.95e-45
Time:                        13:19:37   Log-Likelihood:                -509.89
No. Observations:                 200   AIC:                             1026.
Df Residuals:                     197   BIC:                             1036.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.7749      0.525     10.993      0.000       4.739       6.811
TV             0.0469      0.003     18.173      0.000       0.042       0.052
newspaper      0.0442      0.010      4.346      0.000       0.024       0.064
==============================================================================
Omnibus:                        0.658   Durbin-Watson:                   1.969
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.415
Skew:                          -0.093   Prob(JB):                        0.813
Kurtosis:                       3.122   Cond. No.                         410.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [85]:
lm2 = smf.ols(formula='sales~TV+radio+newspaper', data=df).fit()

In [86]:
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 28 May 2018   Prob (F-statistic):           1.58e-96
Time:                        13:22:40   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [109]:
lm = LinearRegression()


In [90]:
y = df.sales
feature_cols = ['TV','radio','newspaper']
x = df[feature_cols]



In [91]:
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [92]:
lm.intercept_ #Koefisien intercept

2.9388893694594067

In [93]:
lm.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [96]:
lm.score(x,y) #R Square

0.8972106381789521

In [98]:
#set seed
np.random.seed(12345)



In [101]:
nums = np.random.rand(len(df))
mask_large = nums > 0.5


In [103]:
df['Size'] = 'small'
df.loc[mask_large,'Size'] = 'large'
df.head()

TV  radio  newspaper  sales   Size
1  230.1   37.8       69.2   22.1  large
2   44.5   39.3       45.1   10.4  small
3   17.2   45.9       69.3    9.3  small
4  151.5   41.3       58.5   18.5  small
5  180.8   10.8       58.4   12.9  small

In [105]:
df['IsLarge'] = df.Size.map({'small':0, 'large':1}) 
df.head()

TV  radio  newspaper  sales   Size  IsLarge
1  230.1   37.8       69.2   22.1  large        1
2   44.5   39.3       45.1   10.4  small        0
3   17.2   45.9       69.3    9.3  small        0
4  151.5   41.3       58.5   18.5  small        0
5  180.8   10.8       58.4   12.9  small        0

In [110]:
y = df.sales
feature_cols = ['TV','radio','newspaper','IsLarge']
x = df[feature_cols]

In [111]:
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [112]:
lm.intercept_ 

2.948678609864638

In [114]:
lm.coef_

array([ 0.04576141,  0.18860311, -0.00104482, -0.02095199])

In [127]:
np.random.seed(123456)
nums = np.random.rand(len(df))
mask_suburban = (nums>0.33) & (nums<0.66)
mask_urban = nums > 0.66
df['Area'] = 'rural'
df.loc[mask_suburban,'Area'] = 'suburban'
df.loc[mask_urban,'Area'] = 'urban'
df.head()

TV  radio  newspaper  sales   Size  IsLarge      Area
1  230.1   37.8       69.2   22.1  large        1     rural
2   44.5   39.3       45.1   10.4  small        0     urban
3   17.2   45.9       69.3    9.3  small        0     rural
4  151.5   41.3       58.5   18.5  small        0     urban
5  180.8   10.8       58.4   12.9  small        0  suburban

In [128]:
#create 3 dummy variable
area_dummies = pd.get_dummies(df.Area, prefix='Area').iloc[:,1:]
data = pd.concat([df,area_dummies],axis=1)
data.head()

TV  radio  newspaper  sales   Size  IsLarge      Area  Area_suburban  \
1  230.1   37.8       69.2   22.1  large        1     rural              0   
2   44.5   39.3       45.1   10.4  small        0     urban              0   
3   17.2   45.9       69.3    9.3  small        0     rural              0   
4  151.5   41.3       58.5   18.5  small        0     urban              0   
5  180.8   10.8       58.4   12.9  small        0  suburban              1   

   Area_urban  
1           0  
2           1  
3           0  
4           1  
5           0

In [129]:
y = data.sales
feature_cols = ['TV','radio','newspaper','Area_suburban','Area_urban']
x = data[feature_cols]

In [130]:
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [131]:
lm.coef_

array([ 0.0458023 ,  0.18761682, -0.00101815, -0.1178903 ,  0.25352196])