In [68]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from collections import OrderedDict
import seaborn as sns
from pandas.tools import plotting
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, export_graphviz, DecisionTreeRegressor
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from collections import Counter
from statistics import mode

In [127]:
house_train = pd.read_csv('train.csv',index_col=0)
house_train.shape

(1460, 80)

In [50]:
train['MasVnrArea'].head()

Id
1    196.0
2      0.0
3    162.0
4      0.0
5    350.0
Name: MasVnrArea, dtype: float64

In [51]:
train['MasVnrArea'].unique()

array([1.960e+02, 0.000e+00, 1.620e+02, 3.500e+02, 1.860e+02, 2.400e+02,
       2.860e+02, 3.060e+02, 2.120e+02, 1.800e+02, 3.800e+02, 2.810e+02,
       6.400e+02, 2.000e+02, 2.460e+02, 1.320e+02, 6.500e+02, 1.010e+02,
       4.120e+02, 2.720e+02, 4.560e+02, 1.031e+03, 1.780e+02, 5.730e+02,
       3.440e+02, 2.870e+02, 1.670e+02, 1.115e+03, 4.000e+01, 1.040e+02,
       5.760e+02, 4.430e+02, 4.680e+02, 6.600e+01, 2.200e+01, 2.840e+02,
       7.600e+01, 2.030e+02, 6.800e+01, 1.830e+02, 4.800e+01, 2.800e+01,
       3.360e+02, 6.000e+02, 7.680e+02, 4.800e+02, 2.200e+02, 1.840e+02,
       1.129e+03, 1.160e+02, 1.350e+02, 2.660e+02, 8.500e+01, 3.090e+02,
       1.360e+02, 2.880e+02, 7.000e+01, 3.200e+02, 5.000e+01, 1.200e+02,
       4.360e+02, 2.520e+02, 8.400e+01, 6.640e+02, 2.260e+02, 3.000e+02,
       6.530e+02, 1.120e+02, 4.910e+02, 2.680e+02, 7.480e+02, 9.800e+01,
       2.750e+02, 1.380e+02, 2.050e+02, 2.620e+02, 1.280e+02, 2.600e+02,
       1.530e+02, 6.400e+01, 3.120e+02, 1.600e+01, 

In [47]:
train.isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
LotFrontage       259
GarageCond         81
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageQual         81
BsmtExposure       38
BsmtFinType2       38
BsmtFinType1       37
BsmtCond           37
BsmtQual           37
MasVnrArea          8
MasVnrType          8
Electrical          1
Utilities           0
YearRemodAdd        0
MSSubClass          0
Foundation          0
ExterCond           0
ExterQual           0
Exterior2nd         0
Exterior1st         0
RoofMatl            0
RoofStyle           0
YearBuilt           0
                 ... 
GarageArea          0
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
3SsnPorch           0
BsmtUnfSF           0
ScreenPorch         0
PoolArea            0
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
Functional          0
TotRmsAbvGrd        0
KitchenQua

In [74]:
house_train['LotFrontage']=house_train['LotFrontage'].fillna(0)
house_train['MasVnrArea']=house_train['MasVnrArea'].fillna(0)
house_train['GarageYrBlt'].fillna(house_train['GarageYrBlt'].mode)
for i in house_train.columns:
    house_train[i] = house_train[i].fillna('NA')
objectdf = house_train.select_dtypes(include=['object']) #kategorik
objectdf1 = house_train.select_dtypes(exclude=['object']) #non



SalePrice        0
YrSold           0
GrLivArea        0
LowQualFinSF     0
2ndFlrSF         0
1stFlrSF         0
TotalBsmtSF      0
BsmtUnfSF        0
BsmtFinSF2       0
BsmtFinSF1       0
MasVnrArea       0
YearRemodAdd     0
YearBuilt        0
OverallCond      0
OverallQual      0
LotArea          0
LotFrontage      0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
OpenPorchSF      0
MoSold           0
MiscVal          0
PoolArea         0
ScreenPorch      0
3SsnPorch        0
EnclosedPorch    0
WoodDeckSF       0
HalfBath         0
GarageArea       0
GarageCars       0
Fireplaces       0
TotRmsAbvGrd     0
KitchenAbvGr     0
BedroomAbvGr     0
MSSubClass       0
dtype: int64

In [58]:
df = pd.get_dummies(objectdf, columns=objectdf.columns, drop_first=True)
df
df2 = pd.concat([df,objectdf1],axis=1)
df2.info()


(1460, 358)

train['Alley'] = train['Alley'].fillna(value='NA')
train['MasVnrType'] = train['MasVnrType'].fillna(value='None')
train['MasVnrArea'] = train['MasVnrArea'].fillna(value=0)
train['BsmtQual'] = train['BsmtQual'].fillna(value='NA')
train['BsmtCond'] = train['BsmtCond'].fillna(value='NA')
train['BsmtExposure'] = train['BsmtExposure'].fillna(value='NA')
train['BsmtFinType1'] = train['BsmtFinType1'].fillna(value='NA')
train['BsmtFinType2'] = train['BsmtFinType2'].fillna(value='NA')
train['LotFrontage'].fillna(0)
train['GarageYrBlt'].fillna(train['GarageYrBlt'].mode)
train = train.select_dtypes(exclude=['object'])
train = train.select_dtypes(include=['object']).fillna('NA')
#train2 = pd.get_dummies(fixSalesTrain, columns=fixSalesTrain.columns)
fixSalesTrainNum['LotFrontage'].fillna(0)
fixSalesTrainNum['GarageYrBlt'].fillna(fixSalesTrainNum['GarageYrBlt'].mode)

In [37]:
train['GarageYrBlt'].value_counts(dropna=False)

NaN        81
 2005.0    65
 2006.0    59
 2004.0    53
 2003.0    50
 2007.0    49
 1977.0    35
 1998.0    31
 1999.0    30
 1976.0    29
 2008.0    29
 2000.0    27
 2002.0    26
 1968.0    26
 1950.0    24
 1993.0    22
 1962.0    21
 2009.0    21
 1966.0    21
 1965.0    21
 1958.0    21
 1970.0    20
 1996.0    20
 1957.0    20
 2001.0    20
 1997.0    19
 1978.0    19
 1960.0    19
 1954.0    19
 1974.0    18
           ..
 1916.0     5
 1922.0     5
 1936.0     5
 1945.0     4
 1946.0     4
 1982.0     4
 1931.0     4
 1928.0     4
 1935.0     4
 1932.0     3
 1952.0     3
 1921.0     3
 1938.0     3
 2010.0     3
 1910.0     3
 1924.0     3
 1923.0     3
 1947.0     2
 1918.0     2
 1929.0     2
 1914.0     2
 1915.0     2
 1934.0     2
 1937.0     2
 1942.0     2
 1906.0     1
 1927.0     1
 1900.0     1
 1908.0     1
 1933.0     1
Name: GarageYrBlt, Length: 98, dtype: int64

In [34]:
train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [70]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

Id
1       0
2       1
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
30      1
       ..
1431    0
1432    0
1433    0
1434    0
1435    0
1436    0
1437    0
1438    0
1439    0
1440    0
1441    0
1442    0
1443    0
1444    0
1445    0
1446    0
1447    0
1448    0
1449    0
1450    0
1451    0
1452    0
1453    0
1454    0
1455    0
1456    0
1457    0
1458    0
1459    0
1460    0
Name: Condition1_Feedr, Length: 1460, dtype: uint8

In [ ]:
reg = RandomForestRegressor()

steps = [()]

In [75]:
x = df2.drop(['SalePrice'],axis =1)
y = df2['SalePrice']
train_x , val_x, train_y, val_y = train_test_split(x,y, test_size=0.2,random_state=123)

ValueError: labels ['Condition1' 'Condition2'] not contained in axis

In [71]:
dt = DecisionTreeRegressor(random_state=123, min_samples_split=100, min_samples_leaf=10)
dt.fit(train_x,train_y)
dtpred = dt.predict(val_x)

rf = RandomForestRegressor(random_state=123, min_samples_split=100, min_samples_leaf=10)
rf.fit(train_x,train_y)
rfpred = rf.predict(val_x)

gb = GradientBoostingRegressor(random_state=123)
gb.fit(train_x,train_y)
gbpred = gb.predict(val_x)

In [72]:
print(dt.score(val_x,val_y))
print(rf.score(val_x,val_y))
print(gb.score(val_x,val_y))

0.7445144468198779
0.7502465475356056
0.9043557367172534


In [82]:
gb.feature_importances_

array([1.07487651e-02, 0.00000000e+00, 2.09379231e-03, 2.23564047e-03,
       0.00000000e+00, 1.94333376e-03, 6.99142568e-04, 0.00000000e+00,
       2.30059913e-05, 2.35210174e-04, 0.00000000e+00, 8.46587063e-04,
       3.86686234e-04, 0.00000000e+00, 1.36887702e-02, 2.04712781e-04,
       0.00000000e+00, 1.91363391e-04, 1.48024113e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.95617082e-03, 3.43083863e-03,
       0.00000000e+00, 1.50615565e-02, 1.46901728e-03, 0.00000000e+00,
       6.38476260e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.03823110e-03, 0.00000000e+00, 6.90209803e-03,
       2.89916404e-03, 0.00000000e+00, 0.00000000e+00, 1.31682152e-03,
       0.00000000e+00, 1.11416318e-02, 0.00000000e+00, 2.92998990e-03,
       1.61460880e-03, 1.02946875e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.93332789e-03, 0.00000000e+00, 0.00000000e+00,
      

In [128]:
house_test = pd.read_csv('test.csv',index_col=0)
house_test.shape

(1459, 79)

In [104]:
house_test.isnull().sum().sort_values(ascending=False)

PoolQC           1456
MiscFeature      1408
Alley            1352
Fence            1169
FireplaceQu       730
LotFrontage       227
GarageCond         78
GarageQual         78
GarageYrBlt        78
GarageFinish       78
GarageType         76
BsmtCond           45
BsmtQual           44
BsmtExposure       44
BsmtFinType1       42
BsmtFinType2       42
MasVnrType         16
MasVnrArea         15
MSZoning            4
BsmtHalfBath        2
Utilities           2
Functional          2
BsmtFullBath        2
BsmtFinSF2          1
BsmtFinSF1          1
Exterior2nd         1
BsmtUnfSF           1
TotalBsmtSF         1
SaleType            1
Exterior1st         1
                 ... 
OverallQual         0
SaleCondition       0
Heating             0
ExterQual           0
TotRmsAbvGrd        0
YrSold              0
MoSold              0
MiscVal             0
PoolArea            0
ScreenPorch         0
3SsnPorch           0
EnclosedPorch       0
OpenPorchSF         0
WoodDeckSF          0
PavedDrive

In [101]:
for i in house_test.columns:
    house_test[i] = house_test[i].fillna('NA')
objectdf2 = house_test.select_dtypes(include=['object']) #kategorik
objectdf3 = house_test.select_dtypes(exclude=['object']) #non



In [94]:
d = pd.get_dummies(objectdf2, columns=objectdf.columns, drop_first=True)
df
df3 = pd.concat([df,objectdf3],axis=1)


In [105]:
df3.shape

(1461, 348)

In [107]:
for i in house_test.columns:
    print(house_test[i].unique())

[1461 1462 1463 ... 2917 2918 2919]
[ 20  60 120 160  80  30  50  90  85 190  45  70  75 180  40 150]
['RH' 'RL' 'RM' 'FV' 'C (all)' nan]
[ 80.  81.  74.  78.  43.  75.  nan  63.  85.  70.  26.  21.  24. 102.
  94.  90.  79. 110. 105.  41. 100.  67.  60.  73.  92.  84.  39.  88.
  25.  30.  57.  68.  98. 120.  87. 119.  65.  56.  69.  50.  53.  52.
  51.  72.  86. 124.  44.  83.  64.  82.  38.  89.  35.  58.  66.  93.
  31.  76.  28.  61.  95. 129.  59.  77.  96.  47.  34. 117.  48.  62.
  42. 106. 112.  32. 115.  71.  45. 109. 113. 125. 101. 104. 108. 130.
 135.  36.  55. 136.  97.  91.  37.  22. 103.  99.  40. 123.  54. 107.
 150. 160. 195. 128.  33. 118. 134. 155. 126.  46. 149. 200. 121. 131.
 114.  49. 133. 140.]
[11622 14267 13830 ...  1894 20000 10441]
['Pave' 'Grvl']
[nan 'Pave' 'Grvl']
['Reg' 'IR1' 'IR2' 'IR3']
['Lvl' 'HLS' 'Bnk' 'Low']
['AllPub' nan]
['Inside' 'Corner' 'FR2' 'CulDSac' 'FR3']
['Gtl' 'Mod' 'Sev']
['NAmes' 'Gilbert' 'StoneBr' 'BrDale' 'NPkVill' 'NridgHt' 'Blmngt

In [131]:
house_test['SalePrice']

KeyError: 'SalePrice'

In [129]:
list(set(house_test) - set(house_train))

[]

In [132]:
house_train['SalePrice']

Id
1       208500
2       181500
3       223500
4       140000
5       250000
6       143000
7       307000
8       200000
9       129900
10      118000
11      129500
12      345000
13      144000
14      279500
15      157000
16      132000
17      149000
18       90000
19      159000
20      139000
21      325300
22      139400
23      230000
24      129900
25      154000
26      256300
27      134800
28      306000
29      207500
30       68500
         ...  
1431    192140
1432    143750
1433     64500
1434    186500
1435    160000
1436    174000
1437    120500
1438    394617
1439    149700
1440    197000
1441    191000
1442    149300
1443    310000
1444    121000
1445    179600
1446    129000
1447    157900
1448    240000
1449    112000
1450     92000
1451    136000
1452    287090
1453    145000
1454     84500
1455    185000
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64