### SUPERVISED DAY 3 with Mas Adi Wijaya
### Kuis Kahoot Predict Iris species

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from collections import OrderedDict
import seaborn as sns
from pandas.tools import plotting
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV

In [3]:
#load data iris
iris = sns.load_dataset('iris')

In [4]:
#liat data iris 
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
#iris['species']=np.where(iris['species'] == 'sentosa' , 0)

In [6]:
#bikin data X yang Targetnya dihapus dan data Y yang isinya target
X = iris.drop(['species'],axis =1)
Y = iris['species']

In [7]:
#Train Test Split
train_X, test_X, train_y, test_y = train_test_split(X,Y,test_size = 0.2, random_state = 123)

In [9]:
#Bikin model
decisiontree = DecisionTreeClassifier(random_state=123) #definisi model
decisiontree.fit(train_X, train_y) #fit model/bikin model
decisiontreepred = decisiontree.predict(test_X) #predict test_x
pd.DataFrame(decisiontreepred) #hasil prediksi

0
0   versicolor
1    virginica
2    virginica
3   versicolor
4       setosa
5   versicolor
6   versicolor
7       setosa
8       setosa
9   versicolor
10   virginica
11      setosa
12  versicolor
13   virginica
14   virginica
15   virginica
16      setosa
17      setosa
18  versicolor
19      setosa
20      setosa
21   virginica
22      setosa
23   virginica
24      setosa
25      setosa
26      setosa
27   virginica
28   virginica
29      setosa

In [48]:

cm1 = confusion_matrix(test_y,decisiontreepred) #menilai performa dengan bandingin haisl prediksi dengan target yang sebenarnya
sensitivity1 = cm1[1,1] / (cm1[1,0] + cm1[1,1])
specificity1 = cm1[0,0] / (cm1[0,0] + cm1[0,1])

In [50]:
print('Confusion Matrix : \n', cm1)
#print ('Accuracy :', accuracy1)
print('Sensitivy :', sensitivity1)
print('Specificity :', specificity1)
accuracy_score(test_y,decisiontreepred)

Confusion Matrix : 
 [[13  0  0]
 [ 0  6  0]
 [ 0  1 10]]
Sensitivy : 1.0
Specificity : 1.0


0.9666666666666667

In [51]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [52]:
sepal_length = [6.5]
sepal_width = [2.0]
petal_length = [5.0]
petal_width =[5.0]

In [53]:
#bikin data test tanpa label
test = {'sepal_length' : sepal_length,'sepal_width' : sepal_width,'petal_length' : petal_length,'petal_width':petal_width}

In [54]:
test = pd.DataFrame(test)
test

petal_length  petal_width  sepal_length  sepal_width
0           5.0          5.0           6.5          2.0

In [55]:
dtpred1 = decisiontree.predict(test) #prediksi data test tanpa label
dtpred1 = pd.DataFrame(dtpred1)
dtpred1.columns = ['Class']
dtpred1.head()

Class
0  virginica